---
title: "INFO 3370 Final Project"
format: html
editor: visual
---

Load Packages

```{r}
library(readr)
library(haven)
library(tidyverse)
library(scales)
library(dplyr)

df_main <- read_sav("data/usa_00001.sav.gz")
df_main$RACE <- as.numeric(df_main$RACE)

```

Data Cleaning + Preprocessing

```{r}
df_mod <- df_main |>
  filter(INCWAGE > 0) |>
  mutate(RACE = case_when(
    RACE == 1 ~ "White",
    RACE == 2 ~ "Black/African American",
    RACE == 3 ~ "American Indian or Alaska Native",
    RACE == 4 ~ "Chinese",
    RACE == 5 ~ "Japanese",
    RACE == 6 ~ "Other Asian or Pacific Islander"
  )) |>
  mutate(
    HCOVPUB = ifelse(HCOVPUB == 1, "Without public health insurance coverage", "With public health insurance coverage"),
    HCOVPRIV = ifelse(HCOVPRIV == 1, "Without private health insurance coverage", "With private health insurance coverage")
  ) |>
  group_by(RACE) |>
  filter(!is.na(HCOVPUB), !is.na(HCOVPRIV)) |>
  summarize(
    private_insurance_proportion = sum(HCOVPRIV == "With private health insurance coverage") / n(),
    public_insurance_proportion = sum(HCOVPUB == "With public health insurance coverage") / n()
  )

df_median_income <- df_main |>
  group_by(RACE, YEAR) |>
  filter(INCWAGE > 0) |>
  mutate(RACE = case_when(
    RACE == 1 ~ "White",
    RACE == 2 ~ "Black/African American",
    RACE == 3 ~ "American Indian or Alaska Native",
    RACE == 4 ~ "Chinese",
    RACE == 5 ~ "Japanese",
    RACE == 6 ~ "Other Asian or Pacific Islander"
  )) |>
  summarize(median_income = median(INCWAGE, na.rm = TRUE)) 
```

Data Visualization 1

```{r}
ggplot(df_median_income, aes(x = YEAR,y = median_income,color = RACE)) + 
  geom_line() +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title = "Median Income by Race Over Time",
       x = "Year",
       y = "Median Income",
       color = "Race") +
  theme_minimal()

```

Data Visualization 2

```{r}
ggplot(df_mod, aes(x = RACE, y = private_insurance_proportion, fill = RACE)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "Proportion of Individuals with Private Health Insurance by Race",
       x = "Race",
       y = "Proportion",
       fill = "Race") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))
```

Data Visualization 3

```{r}
ggplot(df_mod, aes(x = RACE, y = public_insurance_proportion, fill = RACE)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(title = "Proportion of Individuals with Public Health Insurance by Race",
       x = "Race",
       y = "Proportion",
       fill = "Race") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))
```

Data Visualization 4

```{r}
df_mod_long <- df_mod |>
  pivot_longer(cols = c(private_insurance_proportion, public_insurance_proportion),
               names_to = "Insurance_Type",
               values_to = "Proportion") |>
  mutate(Insurance_Type = ifelse(Insurance_Type == "private_insurance_proportion", "Private", "Public"))

ggplot(df_mod_long, aes(x = RACE, y = Proportion, fill = Insurance_Type, label = scales::percent(Proportion))) +
  geom_col() +
  geom_text(position = position_stack(vjust = 0.5), color = "white") +
  labs(title = "Health Insurance Proportions by Race",
       x = "Race",
       y = "Proportion",
       fill = "Insurance Type") +
  scale_fill_manual(values = c("Private" = "blue", "Public" = "red")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))
```

```{r}
df_main |>
  select(PERWT) |>
  count(PERWT)

```

```{r}
library(dplyr)
library(ggplot2)
library(scales)
#library(Hmisc)

# Define income classes
df_main_income_class <- df_main |>
  mutate(income_class = case_when(
    INCWAGE <= 30000 ~ "Lower Class",
    INCWAGE > 30000 & INCWAGE <= 94000 ~ "Middle Class",
    INCWAGE > 94000 ~ "Upper Class",
    TRUE ~ "Unknown"
  ))

df_mod1 <- df_main_income_class |>
  filter(INCWAGE > 0, YEAR == 2022) |>
  mutate(RACE = case_when(
    RACE == 1 ~ "White",
    RACE == 2 ~ "Black/African American",
    RACE == 3 ~ "American Indian or Alaska Native",
    RACE == 4 ~ "Chinese",
    RACE == 5 ~ "Japanese",
    RACE == 6 ~ "Other Asian or Pacific Islander"
  )) |>
  mutate(
    HCOVPUB = ifelse(HCOVPUB == 1, 0, 1),
    HCOVPRIV = ifelse(HCOVPRIV == 1, 0, 1)
  ) |>
  mutate(insurance_type = if_else(HCOVPUB == 0 & HCOVPRIV == 1, "Private",
                                 if_else(HCOVPUB == 1 & HCOVPRIV == 0, "Public",
                                        if_else(HCOVPUB == 1 & HCOVPRIV == 1, "Both", NA)))
  ) |>
  drop_na(insurance_type) |>
  drop_na(RACE)


ggplot(data = df_mod1, aes(x = insurance_type, fill = RACE)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  facet_grid(rows = vars(income_class)) +
  theme_minimal() +
  labs(
    title = "Type of Health Insurance by Race and Income in the U.S. in 2022",
    x = "Type of Insurance", 
    y = "Percentage",
    fill = "Race"
  )
```

```{r}

df_main_income_class <- df_main |>
  mutate(income_class = case_when(
    INCWAGE <= 30000 ~ "Lower Class",
    INCWAGE > 30000 & INCWAGE <= 94000 ~ "Middle Class",
    INCWAGE > 94000 ~ "Upper Class",
    TRUE ~ "Unknown"
  ))

df_mod3 <- df_main_income_class |>
  filter(INCWAGE > 0, !is.na(YEAR) & YEAR >= 2010) |>
  mutate(RACE = case_when(
    RACE == 1 ~ "White",
    RACE == 2 ~ "Black/African American",
    RACE == 3 ~ "American Indian or Alaska Native",
    RACE == 4 ~ "Chinese",
    RACE == 5 ~ "Japanese",
    RACE == 6 ~ "Other Asian or Pacific Islander",
    TRUE ~ "Other/Unknown"  
  )) |>
  mutate(
    HCOVPUB = ifelse(HCOVPUB == 1, "Public", "No Public"),
    HCOVPRIV = ifelse(HCOVPRIV == 1, "Private", "No Private"),
    insurance_type = case_when(
      HCOVPUB == "Public" & HCOVPRIV == "Private" ~ "Both",
      HCOVPUB == "Public" ~ "Public Only",
      HCOVPRIV == "Private" ~ "Private Only",
      TRUE ~ "No Insurance"  
    )
  )

ggplot(data = df_mod3, aes(x = YEAR, fill = insurance_type)) +
  geom_bar(position = "fill", stat = "count") +
  scale_x_continuous(breaks = seq(2010, 2020, by = 5)) +  
  scale_y_continuous(labels = scales::percent_format()) +
  facet_grid(RACE ~ income_class, scales = "free_x", space = "free_x") +
  theme_minimal() +
  theme(
    strip.text.y = element_text(angle = 0),  
    axis.text.y = element_blank()) +
  labs(
    title = "Trends in Health Insurance by Race and Income in the U.S. (2010 onwards)",
    x = "Year",
    y = "Percentage",
    fill = "Type of Insurance"
  )
```

```{r}

df_main_income_class <- df_main |>
  mutate(income_class = case_when(
    INCWAGE <= 30000 ~ "Lower Class",
    INCWAGE > 30000 & INCWAGE <= 94000 ~ "Middle Class",
    INCWAGE > 94000 ~ "Upper Class",
    TRUE ~ "Unknown"
  ))

processed_ins <- df_main_income_class |>
  filter(INCWAGE > 0, YEAR == 2022) |>
  mutate(RACE = case_when(
    RACE == 1 ~ "White",
    RACE == 2 ~ "Black/African American",
    RACE == 3 ~ "American Indian or Alaska Native",
    RACE == 4 ~ "Chinese",
    RACE == 5 ~ "Japanese",
    RACE == 6 ~ "Other Asian or Pacific Islander"
  )) |>
  mutate(
    HCOVPUB = ifelse(HCOVPUB == 1, "Public", "No Public"),
    HCOVPRIV = ifelse(HCOVPRIV == 1, "Private", "No Private"),
    insurance_type = case_when(
      HCOVPUB == "Public" & HCOVPRIV == "Private" ~ "Both",
      HCOVPUB == "Public" ~ "Public Only",
      HCOVPRIV == "Private" ~ "Private Only",
      HCOVPUB == "No Public" & HCOVPRIV == "No Private" ~ "None"
    )
  ) |>
  drop_na(RACE) 

ggplot(data = processed_ins, aes(x = insurance_type, fill = RACE)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_grid(rows = vars(income_class)) +
  theme_minimal() +
  labs(
    title = "Type of Health Insurance by Race and Income in the U.S. in 2022",
    x = "Type of Insurance", 
    y = "Percentage",
    fill = "Race"
  ) 

```
